In [12]:
import pandas as pd
df=pd.read_csv("C:\\Users\\jeeva\\OneDrive\\Desktop\\car_sales.csv")
df

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [13]:
df.to_csv("cars.csv",index=False)
df1=pd.read_csv("cars.csv")
df1

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [14]:
df1["Price"]=df1["Price"].apply(lambda x:float(x[1:].replace(',','')))
df1

     Make Colour  Odometer (KM)  Doors    Price
0  Toyota  White         150043      4   4000.0
1   Honda    Red          87899      4   5000.0
2  Toyota   Blue          32549      3   7000.0
3     BMW  Black          11179      5  22000.0
4  Nissan  White         213095      4   3500.0
5  Toyota  Green          99213      4   4500.0
6   Honda   Blue          45698      4   7500.0
7   Honda   Blue          54738      4   7000.0
8  Toyota  White          60000      4   6250.0
9  Nissan  White          31600      4   9700.0

In [15]:
toyota=df1[(df1["Make"]=="Toyota")&(df1["Price"]<=5000)]
toyota

     Make Colour  Odometer (KM)  Doors   Price
0  Toyota  White         150043      4  4000.0
5  Toyota  Green          99213      4  4500.0

In [17]:
allcars=df1[df1["Price"]<=5000]
allcars

     Make Colour  Odometer (KM)  Doors   Price
0  Toyota  White         150043      4  4000.0
1   Honda    Red          87899      4  5000.0
4  Nissan  White         213095      4  3500.0
5  Toyota  Green          99213      4  4500.0